// resources/js/components/comments/Comment.vue
<template>

    <div class="mt-3">

        <div class="card rounded-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        <p class="fw-bold">{{ username }}</p>
                    </div>
                    <div class="col-12">
                        <p>{{ content }}</p>
                    </div>
                    <div class="col-12">
                        <a class="link" @click="changeReplyVisibility">
                            <div v-if="!isReplyHidden">
                                Reply
                            </div>
                            <div v-else>
                                Cancel
                            </div>
                        </a>
                        <new-comment v-if="isReplyHidden" :id="id"></new-comment>
                    </div>
                </div>
            </div>
        </div>

        <div class="ms-3">
            <slot></slot>
        </div>

    </div>

</template>

<script>
import { ref } from 'vue'
import NewComment from './NewComment'

export default {
    props: {
        username: {
            required: true,
            type: String
        },
        content: {
            required: true,
            type: String
        },
        id: {
            required: true,
            type: Number
        }
    },
    setup(props) {
        let isReplyHidden = ref(false)

        const changeReplyVisibility = () => {
            isReplyHidden.value = !isReplyHidden.value
            console.log(isReplyHidden.value)
        }

        return {
            changeReplyVisibility,
            isReplyHidden,
            username: props.username,
            content: props.content,
        }
    },
    components: {
        NewComment
    }
}
</script>

        NewComment

// resources/js/components/comments/Comment.jsx
import React, { useState } from "react";
import PropTypes from "prop-types";
import NewComment from "./NewComment";

const Comment = (props) => {
    const { loading, setLoading, comment } = props;
    const [isOpen, setIsOpen] = useState(false);

    return (
        <>
            <div className="mt-3">
                <div className="card rounded-3 shadow-sm">
                    <div className="card-body">
                        <div className="row">
                            <div className="col-12">
                                <p className="h4 fw-bold">
                                    {comment.attributes.username}
                                </p>
                            </div>
                            <div className="col-12">
                                <p>{comment.attributes.content}</p>
                            </div>
                            <div className="col-12">
                                <a
                                    className="link"
                                    onClick={() => setIsOpen(!isOpen)}
                                >
                                    {!isOpen ? "Reply" : "Cancel"}
                                </a>
                                <div className="mt-4">
                                    {isOpen && (
                                        <NewComment
                                            setIsOpen={setIsOpen}
                                            parentId={comment.attributes.id}
                                            setLoading={setLoading}
                                            loading={loading}
                                        />
                                    )}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

Comment.propTypes = {
    comment: PropTypes.object.isRequired,
};

export default Comment;
